### ISSUE TITLE
官方源已经更新

### ISSUE THREAD

**Issue by silencebbb** [ygcaicn/v2ray-heroku-undone#2]
https://github.com/v2fly/v2ray-core/releases/tag/v4.28.1

**Comment by ygcaicn** [comment]
ok,已更新

**Comment by playnetcn** [comment]
@ygcaicn 能否在heroku部署界面里面增加一个添加项，里面写上v2ray的版本号，例如v4.28.2，写哪个版本就去官网取哪个版本部署，这样官网频繁升级的时候，你这个就不需要再维护修改了，部署的时候就取添写的版本上传到服务端就可以了。
