### ISSUE TITLE
服务端更新官网最新版本的方法

### ISSUE THREAD

**Issue by playnetcn** [ygcaicn/v2ray-heroku-undone#3]
官网不定时升级程序，服务端也得跟着不定时更新版本，可否采用如下方法，这个固定连接就可以获取到最新版本。
V2RAY_URL="https://github.com/v2fly/v2ray-core/releases/download/$V_VER/v2ray-linux-64.zip"
改为
V2RAY_URL="https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip"
原来的代码是否可以参照下面网址修改一下？减少维护。
 V_VER=`wget -qO- "https://api.github.com/repos/v2fly/v2ray-core/releases/latest" | sed -n -r -e 's/.*"tag_name".+?"([vV0-9\.]+?)".*/\1/p'`
  [[ -z "${V_VER}" ]] && V_VER="v4.28.2"

原内容来源于如下网址，点击连接。
https://github.com/v2ray/dist/commit/7e4c98117b21bbe1c5659ba91854affca0424eb8

**Comment by ygcaicn** [comment]
已更新

**Comment by playnetcn** [comment]
@ygcaicn 咨询一个问题，如果官网v2ray更新了，我还需要手工重新部署这个服务端程序？

**Comment by ygcaicn** [comment]
> @ygcaicn 咨询一个问题，如果官网v2ray更新了，我还需要手工重新部署这个服务端程序？

不需要重新部署，在heroku中重启一下app或者（10分钟没有活动连接app会休眠，再次有连接后会被唤醒）这两种情况都会拉取最新。
